---
- hosts: bolt
  sudo: yes
  tasks:
    - name: Install python-pip python-devel build-essential
      apt: pkg={{item}} update_cache=yes
      with_items:
        - python-pip
        - python-dev
        - build-essential

    - name: Upgrade pip
      pip: name=pip extra_args='-U'

    - name: Upgrade virtualenv
      pip: name=virtualenv extra_args='-U'

    - name: Install fabric-bolt
      pip: name=fabric-bolt extra_args='-U'
